services:
    freshrss:
        image: freshrss/freshrss:alpine
        container_name: freshrss
        restart: unless-stopped
        ports:
            - "45690:80"
        volumes:
            - data:/var/www/FreshRSS/data
        environment:
            TZ: Asia/Makassar
            CRON_MIN: "*/20"

volumes:
    data:
